- .github/workflows/sonar_cloud.yaml
- build.gradle
기준 test coverage는 0%로 세팅해 두었습니다!
> [PURPLE-6] sonarcloud 셋업

- build.gradle
- src/main/java/com/pikachu/purple/common/config/SwaggerConfig.java
> [PURPLE-18] Swagger 구축

- .github/workflows/dev-server-deployer.yaml
- docker login시 비밀번호 암호화가 되지 않은 채 .docker/config.json에 저장됨으로 에러가 발생합니다.
- --password-stdin을 사용하여 비밀번호가 노출되지 않게 방지하였습니다.
> [PURPLE-21] CD docker login 수정

- compose-dev.yaml
- 카카오 로그인시 token 관리를 위해 redis를 도입했습니다.
- 추후 캐시, 분산락 등에 적용할 예정입니다.
> [PURPLE-51] Redis 구축

- .github/workflows/dev-server-deployer.yaml
- 기존 타켓 경로인 ~/app에서 ~/app/docker로 변경하였습니다.
> [PURPLE-000] docker compose file 경로 수정

- src/main/java/com/pikachu/purple/bootstrap/common/config/SwaggerConfig.java
- src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
- src/main/resources/application.yaml
> [PURPLE-000] CORS 해제

- src/main/java/com/pikachu/purple/PurpleApplication.java
- src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
- src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginTryResponse.java
- src/main/java/com/pikachu/purple/bootstrap/common/config/SwaggerConfig.java
- src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
- src/main/resources/application.yaml
login try 응답 json 변환 안되는 문제 해결
> [PURPLE-000] login try 응답 json 변환 안되는 문제 해결

- src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginTryResponse.java
- src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
> [PURPLE-000] CORS 해결

- src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
CORS 프론트 IP로 제한적 허용
dev, localhost 의 FE IP를 허용합니다.
> [PURPLE-000] CORS 프론트 IP로 제한적 허용

- src/main/java/com/pikachu/purple/PurpleApplication.java
- src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java
- src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
- src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java
- src/main/java/com/pikachu/purple/application/user/vo/tokens/AccessToken.java
- src/main/java/com/pikachu/purple/application/user/vo/tokens/JwtToken.java
- src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java
- src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
- src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginResponse.java
- src/main/java/com/pikachu/purple/bootstrap/common/config/SwaggerConfig.java
- src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
- src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java
- src/main/java/com/pikachu/purple/bootstrap/common/security/AuthorizationInterceptor.java
- src/main/java/com/pikachu/purple/bootstrap/common/security/JwtAuthenticationFilter.java
- src/main/java/com/pikachu/purple/bootstrap/common/security/Secured.java
- src/main/java/com/pikachu/purple/bootstrap/common/security/UserSecurityContext.java
- src/main/java/com/pikachu/purple/bootstrap/common/vo/UserAuthentication.java
- src/main/java/com/pikachu/purple/support/security/auth/Authentication.java
- src/main/java/com/pikachu/purple/support/security/auth/SecurityContext.java
- src/main/java/com/pikachu/purple/support/security/auth/SecurityContextHolder.java
- src/main/java/com/pikachu/purple/support/security/common/id/IdGenerator.java
- src/main/resources/application.yaml
스프링 시큐리티 없이 인증 필터 및 인가 인터셉터를 구현했습니다!
자세한 문서화는 Refresh Token 갱신 API 이후에 작성하겠습니다 :)
PS) Url vo는 java.net.URI에서 제공하는 URI를 이용하면 될 것 같습니다. 추후 URI로 모두 대체하겠습니다!
> [PURPLE-82] 로그인 인증 필터 및 인가 인터셉터 구현

- src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
* 기존 소셜 로그인 로직에서 회원가입 로직 연결하였습니다!
> [PURPLE-89] 회원가입 로직 연결

- .github/workflows/dev-server-deployer.yaml
* docker compose down 옵션을 통해 컨테이너 일괄 삭제 후, pull 하도록 수정
> [PURPLE-90] CD Workflow 수정

- src/main/java/com/pikachu/purple/bootstrap/common/dto/ErrorResponse.java
- src/main/java/com/pikachu/purple/bootstrap/common/dto/SuccessResponse.java
- src/main/java/com/pikachu/purple/bootstrap/common/exception/GlobalExceptionHandler.java
- API 응답값을 표준화하였습니다.
- SuccessResponse는 timeStamp, responseData로 구성됩니다.
- ErrorResponse는 errorCode, errorStatus, timeStamp로 구성됩니다.
> [PURPLE-93] API 응답값 표준화

- src/main/java/com/pikachu/purple/application/perfume/util/RecommendNotesProvider.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> [PURPLE-97] 유저 선호도 기반 추천 향수 목록 조회 리팩토링

- build.gradle
- src/main/java/com/pikachu/purple/bootstrap/common/exception/BusinessException.java
- src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java
- src/main/java/com/pikachu/purple/infrastructure/s3/adapter/ImageUrlS3Adaptor.java
- src/main/java/com/pikachu/purple/infrastructure/s3/common/S3Config.java
- src/main/resources/application.yaml
- 기본적인 세팅만 하였습니다. 세부적인 정책은 작업을 하면서 진행하면 될것 같습니다!
> [PURPLE-100] S3 셋업

- src/main/java/com/pikachu/purple/bootstrap/common/config/WebMvcConfig.java
* FE와의 로그인 리다이렉션 테스트를 위해 cors를 전면 해제하였습니다.
> [PURPLE-000] cors 모든 경로에 대해 해제 설정

- .github/workflows/dev-server-deployer.yaml
* github checkout v2 -> v4로 버전 변경
> [PURPLE-000] github checkout v4

- .github/workflows/dev-server-deployer.yaml
* 로그인 없이는 보안 그룹 접근이 어려워 다음과 같은 코드를 추가하였습니다
> [PURPLE-000] 보안 그룹 접근 허용을 위한 aws credentials 스크립트 추가

- compose-dev.yaml
- src/main/resources/application.yaml
* CD 오류 해결을 위해 compose 파일 내 환경변수 주입 위치를 수정하였습니다!
> [IDLE-000] compose 파일 내 환경변수 주입 위치 변경

- compose-dev.yaml
> chore : 컴포즈 파일 환경변수 주입 위치 변경

- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- user API 중 검색 기록에 관련된 API에 @Secured를 추가하였습니다.
> [PURPLE-000] @Secured 추가

- .github/codeowners
> [PURPLE-000] codeowners 수정

- src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
- src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
* @Secured 어노테이션을 임시로 제거하였습니다.
> [PURPLE-000] @Secured 어노테이션 임시 제거

- src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/common/security/JwtAuthenticationFilter.java
- src/main/java/com/pikachu/purple/support/security/auth/vo/JwtClaims.java
* token resolve 로직 내에서 parameter 값 전달 중, 문자열 구분자 `""` 가 삽입되는 문제를 해결합니다.
> [PURPLE-000] token resolve 로직에서 "" 문자열 따옴표가 삽입되는 문제 해결

- src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java
* refresh token API 내 substring 로직 제거
> [PURPLE-000] refresh token 재발급 API내 substring 로직 제거

- src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
- src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
* 에러 처리를 위해 임시로 제거했던 @Secured 어노테이션을 다시 추가하였습니다.
> [PURPLE-000] @Secured 어노테이션 추가

- src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java
- src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
- src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
- src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginResponse.java
- 최초 로그인(회원가입) 여부에 따라, 온보딩 혹은 메인페이지로 이동
- true = 온보딩 / false = 메인페이지
- 코멘트 토픽(별점, 지속력, 시야주, 계절감/시간, 성별)
- 코드 컨벤션에 따른 리팩토링
> [PURPLE-130] 최초 로그인(회원가입) 여부 반환

- src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeAccordRepository.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
- src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeAccordDomainService.java
- src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeAccordDomainServiceImpl.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeAccordJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeAccordJpaRepository.java
- 향수어코드에 대해 어코드 값 기준으로 order by desc 적용
> [PURPLE-132] 향수어코드 order by desc 적용

- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticId.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/RatingStatisticId.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/RatingStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/userevaluation/entity/UserEvaluationJpaEntity.java
- 코멘트 토픽 관련 테이블 반영
- 코멘트 토픽 조회
- 코멘트 토픽에 관련된 데이터 통계
- 향수 상세 페이지에서의 리뷰 조회
- 자세한 리뷰 수정
> [PURPLE-131] 코멘트 토픽 관련 테이블 설계

- src/main/java/com/pikachu/purple/application/perfume/common/dto/BrandPerfumesDTO.java
- src/main/java/com/pikachu/purple/application/perfume/port/in/PerfumeGetByBrandsUseCase.java
- src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeGetByBrandsApplicationService.java
- src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java
- src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/dto/response/GetPerfumeByBrandsResponse.java
- src/main/java/com/pikachu/purple/domain/perfume/Perfume.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
- 온보딩에서 선택한 향수브랜드의 향수 조회값을 그룹화해서 반환하는 것으로 바꿨습니다.
> [PURPLE-142] 온보딩에서 선택한 향수브랜드의 향수 조회 반환값 수정

- src/main/java/com/pikachu/purple/application/rating/port/in/RatingCreateOnboardingUseCase.java
- src/main/java/com/pikachu/purple/application/rating/port/in/RatingCreateUseCase.java
- src/main/java/com/pikachu/purple/application/rating/port/out/RatingRepository.java
- src/main/java/com/pikachu/purple/application/rating/service/application/RatingCreateOnboardingApplicationService.java
- src/main/java/com/pikachu/purple/application/rating/service/application/RatingDeleteApplicationService.java
- src/main/java/com/pikachu/purple/application/rating/service/domain/RatingDomainService.java
- src/main/java/com/pikachu/purple/application/rating/service/domain/impl/RatingDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/ReviewCreateDetailApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/ReviewCreateSimpleApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/ReviewDeleteApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/rating/controller/RatingController.java
- src/main/java/com/pikachu/purple/domain/review/Review.java
- src/main/java/com/pikachu/purple/domain/review/enums/ReviewType.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/common/ReviewType.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/rating/adaptor/RatingJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/rating/repository/RatingJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ReviewJpaEntity.java
- Review Entity에 reviewType의 컬럼을 추가해, 향수 리뷰 전체 조회시 구분점을 두었습니다.
- Review 엔티티에 RatingId를 삭제하였습니다.
> [PURPLE-143] Review Entity 수정에 따른 로직 변경

- build.gradle
- src/main/java/com/pikachu/purple/infrastructure/redis/annotation/DistributedLock.java
- src/main/java/com/pikachu/purple/infrastructure/redis/annotation/aop/AopForTransaction.java
- src/main/java/com/pikachu/purple/infrastructure/redis/annotation/aop/DistributedLockAop.java
- src/main/java/com/pikachu/purple/infrastructure/redis/common/RedisConfig.java
- src/main/java/com/pikachu/purple/infrastructure/redis/util/SpringELParser.java
- src/main/resources/application.yaml
- 동시성 문제 해결을 위한 분산락 어노테이션 구현
- `@DistributedLock` 
- 분산락 적용 전
- 분산락 적용 후
> [PURPLE-145] 분산락을 위한 어노테이션 구현

- src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDTO.java
- src/main/java/com/pikachu/purple/application/perfume/port/in/PerfumeGetByKeywordUseCase.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeGetByKeywordApplicationService.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/dto/response/GetPerfumeByKeywordResponse.java
- src/main/java/com/pikachu/purple/domain/perfume/Perfume.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeJpaEntity.java
- src/main/resources/application.yaml
> [PURPLE-146] 검색 API 반환 값 수정

- src/main/java/com/pikachu/purple/infrastructure/redis/annotation/DistributedLock.java
- src/main/java/com/pikachu/purple/infrastructure/redis/annotation/aop/DistributedLockAop.java
> [PURPLE-148] 분산락 name 속성 추가

- src/main/java/com/pikachu/purple/application/review/port/in/starrating/CreateOrUpdateStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/starrating/DeleteStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/starrating/UpdateStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/StarRatingRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateReviewDetailApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateReviewSimpleApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateReviewApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateOrUpdateStarRatingOnboardingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/DeleteStarRatingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/UpdateStarStarRatingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/StarRatingDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/StarRatingDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/port/out/StarRatingStatisticRepository.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/domain/statistic/StarRatingStatistic.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/StarRatingJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/StarRatingJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/StarRatingStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/user/entity/UserJpaEntity.java
- 향수 별점 집계 로직 수정 및 보완
- onboarding <- increase
- 간단, 자세한 리뷰 작성 <- increase or (decrease & increase)
- 간단 리뷰 수정 <- decrease & increase
- 리뷰 삭제 <- decrease
- 자세한 리뷰 수정 시 해당 집계 로직 추가
- 리뷰 작성 및 수정 실패 시 롤백 처리
> [PURPLE-150] 향수 별점 집계 로직 수정

- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingOnboardingApplicationService.java
- src/main/java/com/pikachu/purple/application/statistic/port/in/starratingstatistic/IncreaseStarRatingStatisticsUseCase.java
- src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/IncreaseStarRatingStatisticsApplicationService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
> [PURPLE-152] 온보딩 별점 부여 시 집계 로직 수정

- src/main/java/com/pikachu/purple/application/review/port/in/reviewevaluation/CreateReviewEvaluationUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/reviewevaluation/GetReviewEvaluationUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewEvaluationRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateReviewDetailApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/reviewevaluation/CreateReviewEvaluationApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/reviewevaluation/GetReviewEvaluationApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewEvaluationDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewEvaluationDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/port/in/evaluationstatistic/DecreaseEvaluationStatisticUseCase.java
- src/main/java/com/pikachu/purple/application/statistic/port/out/EvaluationStatisticRepository.java
- src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/DecreaseEvaluationStatisticApplicationService.java
- src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/IncreaseEvaluationStatisticApplicationService.java
- src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/IncreaseStarRatingStatisticsApplicationService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/EvaluationStatisticDomainService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/StarRatingStatisticDomainService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/EvaluationStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewEvaluationJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ReviewJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewEvaluationJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/EvaluationStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/StarRatingStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/EvaluationStatisticJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/StarRatingStatisticJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/vo/EvaluationStatisticCompositeKey.java
- 평기 집계 로직 구현
- DecreaseEvaluationStatisticUseCase
- IncreaseEvaluationStatisticUseCase
- 상세 리뷰 작성 유스케이스에 로직 적용
- 별점 집계 로직 사소한 리팩토링 
- 상세 리뷰 수정/삭제 시 집계 로직 적용
- 집계로직 스케쥴러 적용
> [PURPLE-151] 향수 평가 집계 로직 구현

- src/main/java/com/pikachu/purple/application/review/port/in/review/GetReviewsDetailWithEvaluationByUpdatedDateUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewEvaluationRepository.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsDetailWithEvaluationByUpdatedDateApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewEvaluationDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/port/out/EvaluationStatisticRepository.java
- src/main/java/com/pikachu/purple/application/statistic/port/out/StarRatingStatisticRepository.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/EvaluationStatisticScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/EvaluationStatisticDomainService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/StarRatingStatisticDomainService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/EvaluationStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/domain/review/Review.java
- src/main/java/com/pikachu/purple/domain/statistic/EvaluationStatistic.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewEvaluationJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ReviewJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewEvaluationJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/EvaluationStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/EvaluationStatisticJpaRepository.java
- 향수 평가 집계 스케쥴러 구현
- 스케쥴러 정책
- 매일 3시 집계 시작
- 전날 집계결과 = 전전날 집계 결과 + 전날 향수 평가 row 합
> [PURPLE-153] 리뷰 평가 집계 스케쥴러 적용

- src/main/java/com/pikachu/purple/application/review/port/in/complaint/CreateComplaintUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ComplaintRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/complaint/CreateComplaintApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ComplaintDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ComplaintDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
- src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
- src/main/java/com/pikachu/purple/domain/review/Complaint.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ComplaintJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ComplaintJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ComplaintJpaRepository.java
> [PURPLE-159] 코멘트 신고 API 구현

- src/main/java/com/pikachu/purple/application/statistic/port/out/EvaluationStatisticRepository.java
- src/main/java/com/pikachu/purple/application/statistic/port/out/StarRatingStatisticRepository.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/EvaluationStatisticScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/service/application/GetPerfumeStatisticByPerfumeIdApplicationService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/EvaluationStatisticDomainService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/StarRatingStatisticDomainService.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/EvaluationStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/domain/perfume/FragranticaEvaluation.java
- src/main/java/com/pikachu/purple/domain/statistic/EvaluationStatistic.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/FragranticaEvaluationJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/EvaluationStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/adaptor/StarRatingStatisticJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/entity/EvaluationStatisticJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/statistic/repository/EvaluationStatisticJpaRepository.java
> [PURPLE-168] 통계(집계) 로직 버그 수정

- src/main/java/com/pikachu/purple/application/review/common/dto/ReviewByUserDTO.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/GetReviewByPerfumeIdAndUserUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewByPerfumeIdAndUserApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetReviewByPerfumeIdAndUserResponse.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewJpaRepository.java
- 향수 상세 페이지 내 내가 평가한 별점 조회 API 개발(별점값 뿐만 아니라 리뷰 수정에 필요한 값까지 포함)
- reviewType으로 간단한 혹은 자세한 리뷰 구별
> [PURPLE-169] 향수 상세 페이지 내가 평가한 별점 조회 API

- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
> [PURPLE-000] 잘못된 API url 형식 수정

- src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
- src/main/java/com/pikachu/purple/bootstrap/batch/api/BatchApi.java
- src/main/java/com/pikachu/purple/bootstrap/batch/controller/BatchController.java
- 별점 집계 오류 케이스 대처
- 수동 배치 API 구현
- 배치 로직 리팩토링 필요(Spring batch 사용)
> [PURPLE-000] 스케쥴 집계 오류 수정 및 스케쥴링 오류 발생 시 수동 배치 수행 API 추가

- src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsByPerfumeIdAndSortTypeApplicationService.java
- src/main/java/com/pikachu/purple/domain/review/enums/SortType.java
- 리뷰 전체 조회 시 sortType의 값을 한글에서 영어로 변경했습니다.
> [PURPLE-170] SortType 수정

- .gitignore
- build.gradle
- buildscript 및 db 연결 설정 추가
- gradle.properties로 연결 정보 관리
> [PURPLE-000] flyway 플러그인 설정 미흡 보완

- src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsByPerfumeIdAndSortTypeApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsDetailWithEvaluationByUpdatedDateApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateReviewDetailApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/statistic/service/domain/impl/StarRatingStatisticDomainServiceImpl.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ComplaintJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/ReviewJpaEntity.java
- 향수 리뷰 전체 조회 API에 isComplained 정보 주입
> [PURPLE-160] 코멘트 리스트 조회 시 사용자 신고여부 정보 추가

- src/main/java/com/pikachu/purple/application/review/common/dto/UserReviewCountsDTO.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/GetUserReviewCountsUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetUserReviewCountsApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
- src/main/java/com/pikachu/purple/application/user/port/in/user/GetUserCountsUseCase.java
- src/main/java/com/pikachu/purple/application/user/port/out/UserRepository.java
- src/main/java/com/pikachu/purple/application/user/service/application/UserSignUpApplicationService.java
- src/main/java/com/pikachu/purple/application/user/service/application/user/GetUserCountsApplicationService.java
- src/main/java/com/pikachu/purple/application/user/service/domain/UserDomainService.java
- src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetUserReviewCountsResponse.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/user/adaptor/UserJpaAdaptor.java
- API 경로: `/perpicks/users/my/review-counts`
> [PURPLE-180] 마이페이지 > 평가한 향수 갯수 & 사용자들이 평가한 향수 수의 평균 조회 API 추가

- src/main/java/com/pikachu/purple/application/review/common/dto/UserReviewCountsDTO.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/GetUserReviewCountsUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetUserReviewCountsApplicationService.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetUserReviewCountsResponse.java
> [PURPLE-182] 사용자가 평가한 향수 개수 조회 API 응답 정보 형식 변경

- src/main/java/com/pikachu/purple/application/review/common/dto/ReviewedBrandDTO.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/GetTopThreeReviewedBrandsUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ReviewRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetTopThreeReviewedBrandsApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ReviewDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ReviewDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetTopThreeReviewedBrandsResponse.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ReviewJpaRepository.java
> [PURPLE-181] 브랜드 평가 개수 순위 조회 API 추가

- src/main/java/com/pikachu/purple/application/user/port/in/user/GetUserProfileByUserUseCase.java
- src/main/java/com/pikachu/purple/application/user/service/application/user/GetUserProfileApplicationService.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetUserProfileResponse.java
- 마이페이지, 사용자 정보 반환 API
- 닉네임
- imageUrl
- email
- 온보딩 과정에서 닉네임 수정 API를 /perpicks/users의 프로필 수정 API를 사용하고 있는데, 새로운 닉네임 수정 API를 생성해 변경할 예정
> [PURPLE-179] 사용자 정보 반환 API

- src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java
- src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
- src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
- src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginResponse.java
- 로그인 후 프론트에서 사용자 정보를 관리하기 위해, response body로 정보를 반환했습니다.
- jwt에 사용자 정보를 추가
> [PURPLE-184] 로그인 시 사용자 정보 반환

- src/main/java/com/pikachu/purple/application/review/port/in/complaint/DeleteComplaintUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/complaint/DeleteComplaintWithReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ComplaintRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/complaint/DeleteComplaintApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/complaint/DeleteComplaintWithReviewApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ComplaintDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ComplaintDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/complaint/api/ComplaintApi.java
- src/main/java/com/pikachu/purple/bootstrap/complaint/controller/ComplaintController.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ComplaintJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ComplaintJpaRepository.java
- src/main/resources/templates/report-complaint.html
- 기존 신고한 리뷰에 대한 신고 취소
- 기존 발송된 이메일에 대한 처리
> [PURPLE-190] 신고 취소 API

- src/main/java/com/pikachu/purple/application/user/port/in/SocialLogoutUseCase.java
- src/main/java/com/pikachu/purple/application/user/port/out/OAuthRepository.java
- src/main/java/com/pikachu/purple/application/user/port/out/SocialLoginPort.java
- src/main/java/com/pikachu/purple/application/user/port/out/UserTokenRepository.java
- src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java
- src/main/java/com/pikachu/purple/application/user/service/application/SocialLogoutApplicationService.java
- src/main/java/com/pikachu/purple/application/user/service/util/OAuthTokenService.java
- src/main/java/com/pikachu/purple/application/user/service/util/SocialLoginService.java
- src/main/java/com/pikachu/purple/application/user/service/util/UserTokenService.java
- src/main/java/com/pikachu/purple/application/user/service/util/impl/OAuthTokenServiceImpl.java
- src/main/java/com/pikachu/purple/application/user/service/util/impl/SocialLoginServiceImpl.java
- src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java
- src/main/java/com/pikachu/purple/application/user/service/util/strategy/KakaoSocialLoginStrategy.java
- src/main/java/com/pikachu/purple/application/user/service/util/strategy/SocialLoginStrategy.java
- src/main/java/com/pikachu/purple/application/user/vo/SocialRefreshTokenRequest.java
- src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java
- src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java
- src/main/java/com/pikachu/purple/bootstrap/common/exception/BusinessException.java
- src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java
- src/main/java/com/pikachu/purple/domain/user/vo/SocialLogoutId.java
- src/main/java/com/pikachu/purple/domain/user/vo/SocialRefreshToken.java
- src/main/java/com/pikachu/purple/infrastructure/client/auth/kakao/adapter/KakaoSocialLoginAdapter.java
- src/main/java/com/pikachu/purple/infrastructure/client/auth/kakao/util/KakaoRefreshTokenClient.java
- src/main/java/com/pikachu/purple/infrastructure/client/auth/kakao/util/KakaoSocialLogoutClient.java
- src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/OAuthTokenRedisAdapter.java
- src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/UserTokenRedisAdapter.java
- src/main/java/com/pikachu/purple/infrastructure/redis/user/entity/OAuthTokenRedisHash.java
- src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/OAuthTokenRedisRepository.java
- src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/impl/OAuthTokenRedisRepositoryImpl.java
- src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/impl/UserSearchHistoryRedisRepositoryImpl.java
- 로그아웃 API 개발
- FeignClient 클래스 통합
- kakao accesstoken 만료 시, 갱신 요청 로직
> [PURPLE-191] 로그아웃 API

- .github/workflows/dev-server-deployer.yaml
- 인프라 재구성에 따라 cd 워크 플로우를 수정했습니다.
> [PURPLE-196] deployer.yaml 수정

- .github/workflows/dev-server-deployer.yaml
- sshpass로 private subnet에 있는 ec2 접속 완료
> [PURPLE-000] Deployer.yaml 주석처리 해제

- .github/workflows/dev-server-deployer.yaml
- deployer.yaml 파일 중 '-name' 부분의 들여쓰기를 수정했습니다.
> [PURPLE-000] 들여쓰기 수정

- .github/workflows/dev-server-deployer.yaml
> [PURPLE-000] compose file 복사 삭제

- src/main/resources/data/crawling_data/Acqua di Parma.json
- src/main/resources/data/crawling_data/Burberry.json
- src/main/resources/data/crawling_data/Bvlgari.json
- src/main/resources/data/crawling_data/Byredo.json
- src/main/resources/data/crawling_data/Calvin Klein.json
- src/main/resources/data/crawling_data/Chanel.json
- src/main/resources/data/crawling_data/Chloé.json
- src/main/resources/data/crawling_data/Clean.json
- src/main/resources/data/crawling_data/Creed.json
- src/main/resources/data/crawling_data/Dior.json
- src/main/resources/data/crawling_data/Diptyque.json
- src/main/resources/data/crawling_data/Ferrari.json
- src/main/resources/data/crawling_data/Giorgio Armani.json
- src/main/resources/data/crawling_data/Gucci.json
- src/main/resources/data/crawling_data/Jimmy Choo.json
- src/main/resources/data/crawling_data/Jo Malone London.json
- src/main/resources/data/crawling_data/John Varvatos.json
- src/main/resources/data/crawling_data/Kenzo.json
- src/main/resources/data/crawling_data/Kiehl's.json
- src/main/resources/data/crawling_data/Lanvin.json
- src/main/resources/data/crawling_data/Le Labo.json
- src/main/resources/data/crawling_data/Lolita Lempicka.json
- src/main/resources/data/crawling_data/Lush.json
- src/main/resources/data/crawling_data/Marc Jacobs.json
- src/main/resources/data/crawling_data/Montblanc.json
- src/main/resources/data/crawling_data/Penhaligon's.json
- src/main/resources/data/crawling_data/Salvatore Ferragamo.json
- src/main/resources/data/crawling_data/Tom Ford.json
- src/main/resources/data/crawling_data/Versace.json
- 기존 크롤링 데이터에 어코드의 레벨이 나누어져 있지 않은 데이터들은 포함되어 있지 않습니다.
- 모든 어코드를 포함하여 크롤링한 결과물입니다.
> [PURPLE-000] 향수 크롤링 데이터 추가

- src/main/java/com/pikachu/purple/application/review/port/in/complaint/DeleteComplaintUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/out/ComplaintRepository.java
- src/main/java/com/pikachu/purple/application/review/service/application/complaint/DeleteComplaintApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/ComplaintDomainService.java
- src/main/java/com/pikachu/purple/application/review/service/domain/impl/ComplaintDomainServiceImpl.java
- src/main/java/com/pikachu/purple/bootstrap/complaint/api/ComplaintApi.java
- src/main/java/com/pikachu/purple/bootstrap/complaint/controller/ComplaintController.java
- src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
- src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ComplaintJpaAdaptor.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/ComplaintJpaRepository.java
- 기존 Complaint API에 있던 리뷰 신고 취소 api를 Review API로 변경했습니다.
- 요청 값을 complaintId -> reviewId로 변경했습니다.
> [PURPLE-199] 리뷰 신고 취소 API 수정

- src/main/java/com/pikachu/purple/application/perfume/common/dto/BrandDTO.java
- src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeAccordDTO.java
- src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDTO.java
- src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDetailDTO.java
- src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeSimpleDTO.java
- src/main/java/com/pikachu/purple/application/perfume/common/dto/RecommendedPerfumeDTO.java
- src/main/java/com/pikachu/purple/application/perfume/common/dto/UserAccordDTO.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByBrandsApplicationService.java
- src/main/java/com/pikachu/purple/domain/accord/Accord.java
- src/main/java/com/pikachu/purple/domain/perfume/Brand.java
- src/main/java/com/pikachu/purple/domain/perfume/Note.java
- src/main/java/com/pikachu/purple/domain/perfume/Perfume.java
- src/main/java/com/pikachu/purple/domain/perfume/PerfumeAccord.java
- src/main/java/com/pikachu/purple/domain/user/UserAccord.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/accord/entity/AccordJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/BrandJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/NoteJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeAccordJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeJpaEntity.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/user/entity/UserAccordJpaEntity.java
- src/main/resources/db/migration/V202412151029234__add_column_korean_name.sql
- 크롤링 데이터에 대한 한글버전 컬럼 추가
- 컬럼이 추가된 Table
- accord
- brand
- perfume
- note
> [PURPLE-201] 한글버전 컬럼 추가

- src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByReviewCountApplicationService.java
- src/main/java/com/pikachu/purple/application/review/common/dto/ReviewWithPerfumeDTO.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetTopThreeReviewedBrandsApplicationService.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetPolarizedUserAccordsByUserApplicationService.java
- src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
- 마이페이지 API 한글화 작업
- 코멘트 수 기반 향수 추천 API 어코드 반환 수정
> [PURPLE-204] DTO 한글 컬럼 반환

- src/main/java/com/pikachu/purple/application/perfume/common/dto/UserAccordDTO.java
- src/main/java/com/pikachu/purple/application/user/common/dto/PolarizedUserAccordDTO.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetPolarizedUserAccordsByUserApplicationService.java
- 메인페이지, 마이페이지 API중에서 반환값에 어코드가 포함된다면 한글값을 포함해서 반환하도록 변경했습니다.
> [PURPLE-211] 메인페이지, 마이페이지 어코드 한글값 추가 반환

- src/main/java/com/pikachu/purple/application/perfume/scheduler/PerfumeScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
- 별점 재집계 스케쥴러 추가
- 향수 평점 재계산 스케쥴러 추가
> [PURPLE-217] 스케쥴러 추가

- src/main/java/com/pikachu/purple/application/perfume/scheduler/PerfumeScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/EvaluationStatisticScheduler.java
- src/main/java/com/pikachu/purple/application/statistic/scheduler/StarRatingStatisticScheduler.java
- src/main/resources/application.yaml
- 별점 집계 스케쥴러: 매일 03시 00분
- 향수 평점 갱신 스케쥴러: 매일 03시 05분
- 향수 평가 집계 스케쥴러: 매일 03시 00분
> [PURPLE-219] 스케쥴러 실행시간 개별 적용

- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingOnboardingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/UpdateStarRatingApplicationService.java
분산락이 적용된 별점 집계 갱신 처리 후 콜백으로 처리하도록 추후 수정
> [PURPLE-000] 향수 평점 갱신 로직 임시 주석 처리

- src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeDetailDTO.java
- src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/GetPerfumeDetailByPerfumeIdUseCase.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
- src/main/java/com/pikachu/purple/util/MathUtil.java
- API로 제공시 무조건 소수 첫째자리까지 반올림하여 제공
- 불필요한 중복 계산 로직 제거
> [PURPLE-222] 향수 평점 정보 제공에 관한 리팩토링

- src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java
- src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/RefreshJwtTokenRequest.java
- src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/SocialLoginRequest.java
- src/main/java/com/pikachu/purple/bootstrap/complaint/api/ComplaintApi.java
- src/main/java/com/pikachu/purple/bootstrap/onboarding/vo/StarRatingVO.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/api/BrandApi.java
- src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
- src/main/java/com/pikachu/purple/bootstrap/review/api/ReviewApi.java
- src/main/java/com/pikachu/purple/bootstrap/review/dto/request/CreateReviewDetailRequest.java
- src/main/java/com/pikachu/purple/bootstrap/review/dto/request/CreateReviewSimpleRequest.java
- src/main/java/com/pikachu/purple/bootstrap/search/api/SearchApi.java
- src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java
- Controller에서 받는 값에 유효성 검증을 추가했습니다.
> [PURPLE-221] Controller 유효성 검증 추가

- src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/IncreaseEvaluationStatisticService.java
> [PERPICK-004] (statistic > evaluationstatistic) IncreaseEvaluationStatisticUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/RecountEvaluationStatisticsService.java
> [PERPICK-005] (statistic > evaluationstatistic) RecountEvaluationStatisticsUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/DecreaseEvaluationStatisticService.java
> [PERPICK-003] (statistic > evaluationstatistic) DecreaseEvaluationStatisticUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/perfume/service/application/brand/GetBrandsService.java
> [PERPICK-008] (perfume > brand) GetBrandsUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/GetStarRatingStatisticsService.java
- src/main/java/com/pikachu/purple/application/statistic/service/application/starratingstatistic/RecountStarRatingStatisticsService.java
- Command 제거
- GetStarRatingStatisticsUseCase
- RecountStarRatingStatisticsUseCase
> [PERPICK-007] (statistic > starratingstatistic) Get/RecountStarRatingStatisticsUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/service/application/complaint/GetComplaintFormService.java
> [PERPICK-015] (review > complaint) GetComplaintFormUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/service/application/reviewevaluation/CreateReviewEvaluationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/reviewevaluation/GetReviewEvaluationService.java
> [PERPICK-027] (review > reviewevaluation) Create/GetReviewEvaluationUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/service/application/complaint/DeleteComplaintWithReviewService.java
> [PERPICK-014] (review > complaint) DeleteComplaintWithReviewUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/like/DeleteLikesUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/like/CreateLikeService.java
- src/main/java/com/pikachu/purple/application/review/service/application/like/DeleteLikeService.java
- src/main/java/com/pikachu/purple/application/review/service/application/like/DeleteLikesService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewApplicationService.java
- Command 제거
- CreateLikeUseCase
- DeleteLikesUseCase
- DeleteLikeUseCase
> [PERPICK-016] (review > like) UseCase 관련 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/mood/GetMoodsUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/mood/GetMoodsService.java
> [PERPICK-017] (review > mood) GetMoodsUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/review/CreateDetailedReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/CreateSimpleReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateDetailedReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateSimpleReviewService.java
- src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
- Command 제거
- CreateReviewDetailUseCase → CreateDetailedReviewUseCase
- CreateReviewSimpleUseCase → CreateSimpleReviewUseCase
> [PERPICK-018] (review > review) CreateReview관련 UseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/review/UpdateDetailedReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/UpdateSimpleReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateDetailedReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateSimpleReviewService.java
- src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
- Command 제거
- UpdateReviewDetailUseCase → UpdateDetailedReviewUseCase
- UpdateReviewSimpleUseCase → UpdateSimpleReviewUseCase
- UpdateReviewUseCase
> [PERPICK-021] (review > review) UpdateReview관련 UseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/service/application/review/GetTopThreeReviewedBrandsService.java
> [PERPICK-026] (review > review) GetTopThreeReviewedBrandsUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewService.java
> [PERPICK-020] (review > review) DeleteReviewUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/RecalculatePerfumeAverageScoresService.java
> [PERPICK-030] (perfume -> perfume) RecalculatePerfumeAverageScoresUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/RecalculatePerfumeAverageScoreService.java
> [PERPICK-031] (perfume > perfume) RecalculatePerfumeAverageScoreUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/review/GetReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewService.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- 메소드명 변경: invoke() -> find()
- userId를 파라미터로 받도록 수정
- GetCurrentUserReviewUseCase → GetReviewUseCase
> [PERPICK-037] (review > review ) GetCurrentUserReviewUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/starrating/GetStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateOrUpdateStarRatingOnboardingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/GetStarRatingService.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/CreateUserAccordApplicationService.java
> [PERPICK-038] (review > starrating) GetStarRatingUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/starrating/CreateStarRatingsOnboardingUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingsOnboardingService.java
- src/main/java/com/pikachu/purple/bootstrap/onboarding/controller/OnboardingController.java
> [PERPICK-039] (review > starrating) CreateStarRatingsOnboardingUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/starrating/CreateStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/starrating/DeleteStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/starrating/UpdateStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/UpdateReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateOrUpdateStarRatingOnboardingApplicationService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/DeleteStarRatingService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/UpdateStarRatingService.java
- userId 파라미터로 받도록 수정
- 메소드명 수정
- 구현체 이름 수정
> [PERPICK-040] (review > starrating) Create/Update/DeleteStarRatingUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/history/service/application/visithistory/GetVisitHistoriesApplicationService.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesService.java
- src/main/java/com/pikachu/purple/application/review/port/in/review/CreateDetailedReviewUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/starrating/CreateOrUpdateStarRatingUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/starrating/GetPerfumeAverageScoreUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateDetailedReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateSimpleReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateOrUpdateStarRatingService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/GetPerfumeAverageScoreService.java
- src/main/java/com/pikachu/purple/bootstrap/review/controller/ReviewController.java
> (review > starrating) 유스케이스 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/SendComplaintUseCase.java
- src/main/java/com/pikachu/purple/application/review/port/in/complaint/SendComplaintUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/SendComplaintService.java
- src/main/java/com/pikachu/purple/application/review/service/application/complaint/CreateComplaintService.java
> [PERPICK-043] (review > complaint) SendComplaintUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/review/port/in/review/GetCurrentAndAverageUserReviewCountsUseCase.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/GetCurrentAndAverageUserReviewCountsService.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- UseCase 클래스 관련 리팩토링
- 명칭 변경: GetUserReviewCountsUseCase -> GetCurrentAndAverageUserReviewCountsUseCase
> [PERPICK-022] (review > review) GetUserReviewCountsUseCase 리팩토링

- src/main/java/com/pikachu/purple/application/perfume/port/in/GetRecommendedPerfumesByUserAccordsUseCase.java
- src/main/java/com/pikachu/purple/application/perfume/service/application/GetRecommendedPerfumesByUserAccordsService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateDetailedReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/review/CreateSimpleReviewService.java
- src/main/java/com/pikachu/purple/application/review/service/application/starrating/CreateStarRatingsOnboardingService.java
- src/main/java/com/pikachu/purple/application/user/port/in/useraccord/CreateUserAccordOnboardingUseCase.java
- src/main/java/com/pikachu/purple/application/user/port/in/useraccord/CreateUserAccordUseCase.java
- src/main/java/com/pikachu/purple/application/user/port/in/useraccord/GetPolarizedUserAccordsUseCase.java
- src/main/java/com/pikachu/purple/application/user/port/in/useraccord/GetTopThreeUserAccordsUseCase.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/CreateUserAccordOnboardingService.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/CreateUserAccordService.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetPolarizedUserAccordsService.java
- src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetTopThreeUserAccordsService.java
- src/main/java/com/pikachu/purple/bootstrap/recommend/controller/RecommendController.java
- src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- Command 제거
- CreateUserAccordOnboardingUseCase
- CreateUserAccordUseCase
- GetPolarizedUserAccordsUseCase
- GetTopThreeUserAccordsUseCase
> [PERPICK-054] (user > useraccord) UserAccord 관련 UseCase 리팩토링

- src/main/java/com/pikachu/purple/application/user/port/out/ImageUploader.java
- src/main/java/com/pikachu/purple/application/user/service/application/user/UpdateProfileService.java
- src/main/java/com/pikachu/purple/application/user/service/application/user/WithdrawUserService.java
- src/main/java/com/pikachu/purple/infrastructure/objectstorage/adapter/ImageUrlS3Adaptor.java
- src/main/java/com/pikachu/purple/infrastructure/objectstorage/common/S3Config.java
- aws 인프라에서 Oracle 인프라로 전환
- infrastructure의 s3 패키지 및 클래스명 변경
> [PERPICK-075] s3 패키지명 및 클래스명 변경
