perfume-pick/purple-server

src/main/java/com/pikachu/purple/application/user/port/in/ConfirmEmailVerificationCodeUseCase.java, src/main/java/com/pikachu/purple/application/user/port/out/UserEmailVerificationRepository.java, src/main/java/com/pikachu/purple/application/user/service/application/ConfirmEmailVerificationCodeService.java, src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java, src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java, src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/EmailVerificationCodeRequest.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/BusinessException.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java, src/main/java/com/pikachu/purple/infrastructure/redis/common/RedisConfig.java, src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/UserEmailVerificationRedisAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/redis/user/entity/UserEmailVerificationRedisHash.java, src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/UserEmailVerificationRedisRepository.java
- 이메일 인증코드에 필요한 값은 email, verifyCode입니다.
- 현재 이메일 인증코드 검증을 할 때 email, verifyCode로 redis에서 값을 찾고 있는데, 두 attribute가 key가 아니라서 verifyCode에 @indexed를 붙여 보조 인덱스로 값을 찾아 검증을 하고 있습니다.
- 이 로직이 좋지 않다고 판단이 들어 이메일 코드전송 api에서 return 값으로 key값인 id를 반환하여 id, verifyCode로 값을 찾는건 어떤지 궁금합니다.
=> [PURPLE-68] 이메일 인증코드 검증 API

src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java, src/main/java/com/pikachu/purple/support/security/SecurityProvider.java
* 인증 정보를 전역적으로 가져올 수 있는 provider를 작성했습니다.
* `getCurrentUserAuthentication()`을 통해 Authentication 객체를 가져와 사용할 수 있어요!
* 현재 커스텀하게 정의한 구현체인 UserAuthentication에는 email, userId를 포함하고 있습니다!
=> [PURPLE-87] 인증 정보 전역 provider 작성

src/main/java/com/pikachu/purple/application/user/port/in/RefreshJwtTokenUseCase.java, src/main/java/com/pikachu/purple/application/user/port/out/UserTokenRepository.java, src/main/java/com/pikachu/purple/application/user/service/application/RefreshJwtTokenApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/domain/UserDomainService.java, src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserDomainServiceImpl.java, src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java, src/main/java/com/pikachu/purple/application/user/vo/tokens/RefreshToken.java, src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java, src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java, src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/RefreshJwtTokenRequest.java, src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/RefreshJwtTokenResponse.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/BusinessException.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java, src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/UserTokenRedisAdapter.java, src/main/java/com/pikachu/purple/infrastructure/redis/user/entity/UserAccessTokenRedisHash.java, src/main/java/com/pikachu/purple/infrastructure/redis/user/repository/UserAccessTokenRedisRepository.java, src/main/java/com/pikachu/purple/support/security/SecurityProvider.java
* 토큰 리프레시 로직 구현하였습니다.
* AccessToken 만료 시, 액세스 토큰 만료 에러가 발생합니다.
* 해당 JwtToken을 이용하여 Refresh Token 갱신 API에 태우면 새로운 access, refresh, jwt token을 제공합니다.
* 만약 해당 RefreshToken도 만료된 경우, 리프레시 토큰 만료 에러가 발생합니다.
* 만료 정책 적용을 위해 JwtToken 저장은 불 필요하다고 판단했습니다. 대신, Access Token을 저장하여 Redis에서 관리하도록 변경하였습니다.
=> [PURPLE-84] Refresh Token 갱신 API

src/main/java/com/pikachu/purple/application/perfume/port/in/PerfumeGetByBrandsUseCase.java, src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java, src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java, src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeServiceImpl.java, src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java, src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeBrandApi.java, src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeBrandController.java, src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java, src/main/java/com/pikachu/purple/bootstrap/perfume/dto/request/GetPerfumeByBrandsRequest.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
- API 응답값을 SuccessResponse, ErrorRepsonse를 이용하여 통일화 하였습니다.
- 온보딩에서 선택한 향수브랜드 조회 API에서 @GetMapping을 사용하므로 기존 @ResponseBody에서 @RequestParam으로 수정하였습니다.
=> [PURPLE-98] API 응답값 통일

src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java, src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java, src/main/resources/application.yaml
* Auth 도메인의 API의 응답 형태를 모두 통일된 구조로 변경하였습니다.
* Swagger 상에서 로그인 API의 최종 리디렉션 url을 명세하였습니다.
* 기존 인가 코드를 발급받는 API를 client쪽으로 지정하는 방향으로 롤백함에 따라 yaml 상의 redirection url을 맞게 수정하였습니다.
=> [PURPLE-105] 로그인 API 응답값 통일

compose-dev.yaml, src/main/resources/application.yaml
* 개발쪽 로그 확인해 봤을 때 기본 active profile이 지정이 안 되어 있어서 default로 실행되고 있더라구요..! 이게 저희 개발서버 DB쪽 이슈랑 연관되는 것 같아서 체킹차 PR 올립니다.
=> [PURPLE-000] 스프링 기본 active profile 지정

src/main/java/com/pikachu/purple/application/common/properties/KakaoSocialLoginProperties.java, src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java, src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/util/UserTokenService.java, src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java, src/main/java/com/pikachu/purple/application/user/service/util/strategy/KakaoSocialLoginStrategy.java, src/main/java/com/pikachu/purple/application/user/service/util/strategy/SocialLoginStrategy.java, src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java, src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java, src/main/java/com/pikachu/purple/bootstrap/auth/dto/response/SocialLoginResponse.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/BusinessException.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/ErrorCode.java, src/main/java/com/pikachu/purple/infrastructure/client/auth/kakao/adapter/KakaoSocialLoginAdapter.java, src/main/java/com/pikachu/purple/support/security/auth/util/JwtTokenProvider.java, src/main/resources/application.yaml
* FE 요청에 따라 로그인 토큰 전달 방식을 redirection에서 response body로 전달되도록 변경합니다.
* 토큰 검증 로직 내 try-catch문 도입을 통해 커스텀 에러로 핸들링되도록 변경하였습니다.
* 커스텀 에러에 대한 리팩토링을 한번 해야할 것 같네요..! 생각보다 핸들링처리하지 않은 에러들도 보여서 API 연결 시에 어려움이 있을수도 있을 것 같네요! 조금 더 꼼꼼하게 엣지 케이스 처리를 해 두어야 할 것 같습니다~
=> [PURPLE-116] 로그인 토큰 전달 방식 redirection에서 response body로 변경

src/main/java/com/pikachu/purple/PurpleApplication.java, src/main/java/com/pikachu/purple/application/favorite/port/in/FavoriteCreateUseCase.java, src/main/java/com/pikachu/purple/application/favorite/port/out/FavoriteRepository.java, src/main/java/com/pikachu/purple/application/favorite/service/application/FavoriteCreateApplicationService.java, src/main/java/com/pikachu/purple/application/favorite/service/domain/FavoriteDomainService.java, src/main/java/com/pikachu/purple/application/favorite/service/domain/impl/FavoriteDomainServiceImpl.java, src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeBrandRepository.java, src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeBrandGetTopThirtyApplicationService.java, src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeBrandDomainService.java, src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeBrandDomainServiceImpl.java, src/main/java/com/pikachu/purple/application/rating/service/application/RatingSaveApplicationService.java, src/main/java/com/pikachu/purple/domain/favorite/Favorite.java, src/main/java/com/pikachu/purple/infrastructure/persistence/favorite/adaptor/FavoriteJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/favorite/entity/FavoriteJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/favorite/repository/FavoriteJpaRepository.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeBrandJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeBrandJpaRepository.java
- PerfumeBrandName Entity 조회 시 정해진 조회 순서대로 정렬하기 위해, Secondary index를 적용했습니다.
- 온보딩 향수 선택 시 인생향수 값도 생성하는 로직으로 변경했습니다.
- BaseEntity를 이용하여, 컬럼이 생성 혹은 업데이트 될 때 Jpa Auditing을 사용하여 자동 업데이트 하게 하였습니다.
- 온보딩 향수 선택 및 평가 시 간단한 리뷰 추가 및 로직 변경
- 간단한 리뷰 CUD
=> [PURPLE-120] PerfumeBrandName entity 수정 및 온보딩 시 인생향수 생성

src/main/java/com/pikachu/purple/application/user/service/application/RefreshJwtTokenApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/util/SocialLoginService.java, src/main/java/com/pikachu/purple/application/user/service/util/impl/UserTokenServiceImpl.java, src/main/java/com/pikachu/purple/bootstrap/common/exception/GlobalExceptionHandler.java, src/main/resources/application.yaml
* Refresh Token API 에러를 해결하였습니다.
* 토큰을 toString()으로 반환하는 과정에서 `""` 해당 기호가 양옆에 추가되어 토큰 생성 시 invalid한 값이 입력되는 문제입니다.
* 에러를 throw하는 과정에서 BusinessException 내에 정의된 static method를 사용하지 않아 ExceptionHandler를 거치지 못하고 500으로 떨어지는 현상을 해결했습니다.
=> [PURPLE-122] Refresh Token API 에러 해결

src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java, src/main/java/com/pikachu/purple/domain/perfume/PerfumeBrand.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeBrandJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java
- nativequery로 작성하다보니, brandName이란 컬럼명이 perfumeBrand와 perfume에서 같아 NonUniqueDiscoveredSqlAliasException 에러가 발생했습니다. 이를 방지하기 위해 alias를 사용해서 컬럼 이름을 변경해주었습니다.
=> [PURPLE-000] @Secured 추가 및 perfumeBrand에 imageUrl 컬럼 추가

src/main/java/com/pikachu/purple/domain/evaluation/FragranticaEvaluation.java, src/main/java/com/pikachu/purple/domain/evaluation/enums/EvaluationCodeType.java, src/main/java/com/pikachu/purple/domain/mainAccord/MainAccord.java, src/main/java/com/pikachu/purple/domain/perfume/PerfumeNote.java, src/main/java/com/pikachu/purple/domain/perfume/enums/PerfumeNoteType.java, src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/entity/EvaluationCodeJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/entity/FragranticaEvaluationJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/mainAccord/entity/MainAccordJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeNoteJpaEntity.java
* 메인어코드(MainAccord), 프라그란티카 평가(FragranticaEvaluation), 평가코드정보(EvaluationCode) 관련 엔티티 및 도메인 추가
* PerfumeNote에 perfumeNoteType(발향 순서, TOP/MIDDLE/BASE) 속성 및 enum 추가
* EvaluationCode와 연관되어 있는 상세 코멘트 쪽 UserEvaluation 엔티티 및 도메인은 다른 PR로 올릴 예정
- perfume, evaluation, review, rating 등 전체적으로 이상한 부분이 있는 지 봐주시면 감사하겠습니다.
=> [PURPLE-124] 향수 상세정보 관련 엔티티 및 도메인 추가

src/main/java/com/pikachu/purple/infrastructure/s3/adapter/ImageUrlS3Adaptor.java
- 사용자 프로필 수정 API에서 S3로 이미지 등록 후, 이미지 url로 조회하면 다운로드 되는 현상을 방지하였습니다.
=> [PURPLE-127] S3 이미지 조회시 다운로드 되는 현상 방지

src/main/java/com/pikachu/purple/application/evaluation/common/dto/FragranticaEvaluationDTO.java, src/main/java/com/pikachu/purple/application/evaluation/common/dto/FragranticaEvaluationDto.java, src/main/java/com/pikachu/purple/application/evaluation/common/dto/MostVotedOption.java, src/main/java/com/pikachu/purple/application/evaluation/port/in/FragranticaEvaluationGetByPerfumeIdUseCase.java, src/main/java/com/pikachu/purple/application/evaluation/port/out/FragranticaEvaluationRepository.java, src/main/java/com/pikachu/purple/application/evaluation/service/application/FragranticaEvaluationGetByPerfumeIdApplicationService.java, src/main/java/com/pikachu/purple/application/evaluation/service/domain/FragranticaEvaluationDomainService.java, src/main/java/com/pikachu/purple/application/evaluation/service/domain/impl/FragranticaEvaluationDomainServiceImpl.java, src/main/java/com/pikachu/purple/application/util/MathUtil.java, src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java, src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java, src/main/java/com/pikachu/purple/bootstrap/perfume/dto/response/GetFragranticaEvaluationsResponse.java, src/main/java/com/pikachu/purple/domain/evaluation/FragranticaEvaluation.java, src/main/java/com/pikachu/purple/domain/evaluation/enums/EvaluationField.java, src/main/java/com/pikachu/purple/domain/evaluation/enums/EvaluationOption.java, src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/adaptor/FragranticaEvaluationJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/entity/FragranticaEvaluationJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/evaluation/repository/FragranticaEvaluationJpaRepository.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeBrandJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
- 프라그란티카 평가 정보 조회 API 구현
- 프라그란티카 평가영역별 최다 득표 결과 조회
- EvaluationField, EvaluationOption enum 정의
- 응답 정보
<details>
<summary>결과 샘플</summary>
<div markdown="2">
```json
{
"timeStamp": "2024-09-05T18:40:43.0223",
"responseData": {
"fragranticaEvaluations": [
{
"fieldCode": "EF001",
"fieldName": "지속력",
"mostVotedOptions": [
{
"optionCode": "EO103",
"optionName": "보통",
"votePercent": 57
}
]
},
{
"fieldCode": "EF002",
"fieldName": "시야주",
"mostVotedOptions": [
{
"optionCode": "EO202",
"optionName": "보통",
"votePercent": 63
}
]
},
{
"fieldCode": "EF003",
"fieldName": "계절감/시간",
"mostVotedOptions": [
{
"optionCode": "EO301",
"optionName": "봄",
"votePercent": 30
},
{
"optionCode": "EO305",
"optionName": "낮",
"votePercent": 27
},
{
"optionCode": "EO302",
"optionName": "여름",
"votePercent": 23
}
]
},
{ …
```
=> [PURPLE-132] 프라그란티카 평가 정보 조회 API 구현

compose-dev.yaml, compose-local.yaml, src/main/java/com/pikachu/purple/infrastructure/redis/common/RedisConfig.java
- 데이터베이스 현상관리를 위해 volume을 설정했습니다.
- api 연동 작업 중 refresh token 만료 주기 대비 빠르게 만료되어, 확인해본 결과 redis 내부 해킹 목적의 스크립트가 적용되어 있었습니다.
- redis 내 비밀번호 설정하여 선 조치했습니다.
=> [PURPLE-156] docker volume 설정 및 redis 비밀번호 추가

src/main/java/com/pikachu/purple/application/review/common/dto/ReviewDTO.java, src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsByPerfumeIdAndSortTypeApplicationService.java
- 향수 리뷰 조회 api 응답정보에 isCurrentUserReview 추가
=> [PURPLE-171] 향수 리뷰 조회 api 응답정보에 isCurrentUserReview 추가

src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeRepository.java, src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java, src/main/java/com/pikachu/purple/application/perfume/service/domain/PerfumeDomainService.java, src/main/java/com/pikachu/purple/application/perfume/service/domain/impl/PerfumeDomainServiceImpl.java, src/main/java/com/pikachu/purple/application/perfume/util/RecommendUserAccordsProvider.java, src/main/java/com/pikachu/purple/application/user/port/in/useraccord/GetTopThreeUserAccordsUseCase.java, src/main/java/com/pikachu/purple/application/user/port/out/UserAccordRepository.java, src/main/java/com/pikachu/purple/application/user/service/application/useraccord/CreateUserAccordApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/application/useraccord/GetTopThreeUserAccordsApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/domain/UserAccordDomainService.java, src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserAccordDomainServiceImpl.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeJpaRepository.java, src/main/java/com/pikachu/purple/infrastructure/persistence/user/adaptor/UserAccordJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/user/repository/UserAccordJpaRepository.java
- 기존 온보딩시 유저 어코드를 최대 5개만 저장했었지만, 불호 노트를 위해 모든 유저 어코드를 저장
=> [PURPLE-165] 선호/불호 노트를 위한 리팩토링

src/main/java/com/pikachu/purple/application/history/service/application/visithistory/GetVisitHistoriesApplicationService.java, src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java, src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByKeywordApplicationService.java, src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumesByReviewCountApplicationService.java, src/main/java/com/pikachu/purple/application/review/port/in/starrating/GetAverageScoreByPerfumeIdUseCase.java, src/main/java/com/pikachu/purple/application/review/port/out/StarRatingRepository.java, src/main/java/com/pikachu/purple/application/review/service/application/starrating/GetAverageScoreByPerfumeIdApplicationService.java, src/main/java/com/pikachu/purple/application/review/service/domain/StarRatingDomainService.java, src/main/java/com/pikachu/purple/application/review/service/domain/impl/StarRatingDomainServiceImpl.java, src/main/java/com/pikachu/purple/domain/perfume/Perfume.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/StarRatingJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/StarRatingJpaRepository.java
- 향수 별점 평균 산출 UseCase 추가
- 향수 ID를 기준으로 해당 별점 전부 select
- score 합산 / 별점 개수, 소숫점 첫번째 자리수까지
- PerfumeDTO, RecommendedPerfumeDTO 관련으로 평점 산출 로직 적용
- 평점 산출 로직 개선 필요
- 별점 업데이터 되는 경우 바로 평점 반영 후 DB 내 perfume.averate_score 업데이트
=> [PURPLE-172] 향수 별점 평균 계산 로직 추가

src/main/java/com/pikachu/purple/application/review/common/dto/ReviewDTO.java, src/main/java/com/pikachu/purple/application/review/common/dto/ReviewWithPerfumeDTO.java, src/main/java/com/pikachu/purple/application/review/port/in/starrating/GetReviewsByUserAndSortTypeUseCase.java, src/main/java/com/pikachu/purple/application/review/port/out/StarRatingRepository.java, src/main/java/com/pikachu/purple/application/review/service/application/starrating/GetReviewsByUserAndSortTypeApplicationService.java, src/main/java/com/pikachu/purple/application/review/service/domain/StarRatingDomainService.java, src/main/java/com/pikachu/purple/application/review/service/domain/impl/StarRatingDomainServiceImpl.java, src/main/java/com/pikachu/purple/application/util/DateUtil.java, src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java, src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java, src/main/java/com/pikachu/purple/bootstrap/user/dto/response/GetReviewsByUserAndSortTypeResponse.java, src/main/java/com/pikachu/purple/domain/review/StarRating.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/StarRatingJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/entity/StarRatingJpaEntity.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/StarRatingJpaRepository.java
- 자신이 작성한 리뷰를 전체 조회합니다.
- 온보딩때 평가한 값까지 포함합니다.
- 최신순으로 조회할 때 수정된 날짜를 기준으로 비교합니다.
- 온보딩때 평가한 값을 간단한/자세한 리뷰로 변경하기 위해 반환값에 perfumeId를 추가했습니다.
- 간단한/자세한 리뷰로 변환을 할 때는 간단한/자세한 리뷰 생성 API를 사용합니다.
=> [PURPLE-186] 자신이 작성한 리뷰 전체 조회 API

src/main/java/com/pikachu/purple/application/review/port/in/like/DeleteAllLikeUseCase.java, src/main/java/com/pikachu/purple/application/review/port/out/LikeRepository.java, src/main/java/com/pikachu/purple/application/review/service/application/like/DeleteAllLikeApplicationService.java, src/main/java/com/pikachu/purple/application/review/service/application/review/DeleteReviewApplicationService.java, src/main/java/com/pikachu/purple/application/review/service/domain/LikeDomainService.java, src/main/java/com/pikachu/purple/application/review/service/domain/impl/LikeDomainServiceImpl.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/LikeJpaAdaptor.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/repository/LikeJpaRepository.java
- 좋아요가 리뷰를 참조하고 있기 때문에, 리뷰에 대한 좋아요 데이터가 존재할 경우 좋아요를 삭제하지 않고 리뷰를 삭제할 시 무결성 보장에 따라 에러가 발생합니다.
- 리뷰를 삭제하기 전 리뷰에 해당하는 좋아요를 삭제하는 로직을 추가했습니다.
=> [PURPLE-188] 리뷰 삭제 API 수정

src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java, src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java, src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java, src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java, src/main/resources/application.yaml
- 로컬, 서버환경에서 카카오 로그인 api를 테스트할 수 있도록 기존 프론트로 리다이렉션하는 방식을 서버로 리다이렉션하여 어느 환경에서나 테스트할 수 있도록 수정하였습니다.
=> [PURPLE-189] 카카오 로그인 redirect uri 서버로 변경

src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginTryUseCase.java, src/main/java/com/pikachu/purple/application/user/port/in/SocialLoginUseCase.java, src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/application/SocialLoginTryApplicationService.java, src/main/java/com/pikachu/purple/application/user/service/util/SocialLoginService.java, src/main/java/com/pikachu/purple/application/user/service/util/impl/SocialLoginServiceImpl.java, src/main/java/com/pikachu/purple/application/user/service/util/strategy/KakaoSocialLoginStrategy.java, src/main/java/com/pikachu/purple/application/user/service/util/strategy/SocialLoginStrategy.java, src/main/java/com/pikachu/purple/bootstrap/auth/api/AuthApi.java, src/main/java/com/pikachu/purple/bootstrap/auth/controller/AuthController.java, src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/SocialLoginRequest.java, src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/SocialLoginTryRequest.java, src/main/resources/application.yaml
- 기존 카카오 로그인 로직은 프론트엔드의 요청 url(http://ip:port)에 따라 동적으로 리디렉션 url을 반환할 수 없는 구조
- 프론트엔드에게 직접 url을 받아 리디렉션 url을 생성 후 반환하는 로직으로 수정
=> [PURPLE-193] 카카오 로그인 API 수정

src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
- 어코드 기반 추천 향수 리스트 조회시 선호 어코드의 값이 존재하지 않으면, 404(선호하는 어코드가 없습니다.) -> 빈 리스트 형태로 수정했습니다.
=> [PURPLE-194] 어코드 기반 추천 향수 리스트 조회시 값이 존재하지 않을 때, 반환 형태 수정

src/main/java/com/pikachu/purple/application/review/common/dto/ReviewByUserDTO.java, src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewByPerfumeIdAndUserApplicationService.java, src/main/java/com/pikachu/purple/infrastructure/persistence/review/adaptor/ReviewJpaAdaptor.java
- 기존 별점 조회를 할 때 평가한 향수가 없다면 404 exception을 반환했습니다.
- 프론트의 요청으로 반환하는 값을 기본값으로 수정했습니다.
=> [PURPLE-200] 향수 상세 페이지 내 별점 조회 API 수정

src/main/java/com/pikachu/purple/bootstrap/search/controller/SearchController.java, src/main/java/com/pikachu/purple/bootstrap/user/api/UserApi.java, src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- 검색 API에서 사용자가 단어를 입력할때 마다 요청을 보내기 때문에 의도치 않은 검색 기록이 많이 남음
- 한 검색에 대해 -> ex) 데이지, 데이지 러브, 데이지 러브 오 ....
- 기존 검색 API에 최근 검색 저장 로직이 포함
- 최근 검색 저장 로직을 API로 분리
- 최종적으로 검색한 결과에서 향수 상세 페이지로 넘어가거나, 키보드 창에서 입력 혹은 검색 버튼을 눌렀을 때만 최근 검색 기록을 저장하도록 변경
=> [PURPLE-205] 최근 검색 기록 저장 API로 분리

src/main/java/com/pikachu/purple/application/review/common/dto/ReviewByUserDTO.java, src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewByPerfumeIdAndUserApplicationService.java, src/main/java/com/pikachu/purple/domain/review/enums/ReviewType.java
- 향수 상세 페이지 내 '평가하기' 별점 조회에서 온보딩때 평가한 향수도 조회할 수 있도록 변경했습니다.
- 기존 ReviewType에 ONBOARDING으로 반환됩니다.
=> [PURPLE-209] 향수 상세 페이지 내 '평가하기' 별점 조회 수정

src/main/java/com/pikachu/purple/application/perfume/service/application/GetPerfumesAndUserAccordsByUserApplicationService.java
- 어코드 기반 추천 향수 조회 API에서 accordName이 누락되어 수정했습니다.
=> [PURPLE-212] 메인페이지 어코드 기반 추천 향수 리스트 수정

src/main/resources/db/migration/V20250117055954__alter_datetime_columns_to_timestamp_columns.sql
- timestamp 타입으로 변경에 따른 TimeZone(Asian/Seoul, +9:00) 자동 적용
- DB 내 데이터는 기존과 동일하게 UTC 기준으로 저장이 되나,
- 자바 스프링으로부터 조회 시 타임존 적용된 시각으로 조회 됨
=> [PURPLE-223] DB 일시 컬럼 타입 변경: datetime -> timestamp

src/main/java/com/pikachu/purple/application/statistic/port/in/GetPerfumeStatisticUseCase.java, src/main/java/com/pikachu/purple/application/statistic/service/application/GetPerfumeStatisticByPerfumeIdService.java, src/main/java/com/pikachu/purple/application/statistic/service/application/GetPerfumeStatisticService.java, src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
=> [PERPICK-011] (statistic) GetPerfumeStatisticByPerfumeIdUseCase 리팩토링

src/main/java/com/pikachu/purple/application/perfume/port/in/perfume/GetPerfumeUseCase.java, src/main/java/com/pikachu/purple/application/perfume/service/application/perfume/GetPerfumeService.java
=> [PERPICK-009] (perfume > perfume) GetPerfumeUseCase 리팩토링

src/main/java/com/pikachu/purple/application/review/service/application/complaint/CreateComplaintService.java, src/main/java/com/pikachu/purple/application/review/service/application/complaint/DeleteComplaintService.java
- Command 제거
- CreateComplaintUseCase
- DeleteComplaintUseCase
=> [PERPICK-013] (review > complaint) Create/DeleteComplaintUseCase 리팩토링

src/main/java/com/pikachu/purple/application/review/port/in/review/GetDetailedReviewsUseCase.java, src/main/java/com/pikachu/purple/application/review/service/application/review/GetDetailedReviewsService.java, src/main/java/com/pikachu/purple/application/statistic/service/application/evaluationstatistic/RecountEvaluationStatisticsService.java
- Command 제거
- GetReviewsDetailWithEvaluationUseCase → GetDetailedReviewsUseCase
=> [PERPICK-025] (review > review) GetReviewsDetailWithEvaluationUseCase 리팩토링

src/main/java/com/pikachu/purple/application/review/port/in/review/GetCurrentUserReviewUseCase.java, src/main/java/com/pikachu/purple/application/review/service/application/review/GetCurrentUserReviewService.java, src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- Command 제거
- GetReviewByPerfumeIdAndUserUseCase → GetCurrentUserReviewUseCase
=> [PERPICK-023] (review > review) GetReviewByPerfumeIdAndUserUseCase 리팩토링

src/main/java/com/pikachu/purple/application/review/port/in/review/GetReviewsUseCase.java, src/main/java/com/pikachu/purple/application/review/service/application/review/GetReviewsService.java, src/main/java/com/pikachu/purple/bootstrap/perfume/controller/PerfumeController.java
- Command 제거
- GetReviewsByPerfumeIdAndSortTypeUseCase → GetReviewsUseCase
=> [PERPICK-024] (review > review) GetReviewsByPerfumeIdAndSortTypeUseCase 리팩토링

src/main/java/com/pikachu/purple/application/history/port/in/searchhistory/CreateSearchHistoryUseCase.java, src/main/java/com/pikachu/purple/application/history/service/application/searchhistory/CreateSearchHistoryService.java, src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- Command 제거
- CreateSearchHistoryUseCase
=> [PERPICK-034] (history > history) CreateSearchHistoryUseCase 리팩토링

src/main/java/com/pikachu/purple/application/history/port/in/searchhistory/DeleteSearchHistoriesUseCase.java, src/main/java/com/pikachu/purple/application/history/service/application/searchhistory/DeleteSearchHistoriesService.java, src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- Command 제거
- DeleteSearchHistoriesUseCase
=> [PERPICK-035] (history > history) DeleteSearchHistoriesUseCase 리팩토링

src/main/java/com/pikachu/purple/application/history/port/in/searchhistory/GetSearchHistoriesUseCase.java, src/main/java/com/pikachu/purple/application/history/service/application/searchhistory/GetSearchHistoriesService.java, src/main/java/com/pikachu/purple/bootstrap/user/controller/UserController.java
- Command 제거
- GetSearchHistoriesUseCase
=> [PERPICK-036] (history > history) GetSearchHistoriesUseCase 리팩토링
